#!/bin/bash
REALM="$1"
CHAR="$2"

RESULT=$(curl -s -l "https://eu.api.battle.net/wow/character/$REALM/$CHAR?locale=en_GB&apikey=dudk36c9ejqg3mjb6qm9qmhv4ckde5wh")

function getData {
	 echo $RESULT | jq .$1 | fold -s
}

if [ -n "$3" ]
then
	getData $3
else
	echo $"Usage: $0 realm character {level|name|achievementPoints|thumbnail|++}"
	exit 1 
fi

