#!/bin/python
from os import listdir
from os.path import isfile, join

dir="/home/oleerik/.PlayOnLinux/shortcuts/"

onlyFiles = [ f for f in listdir(dir) if isfile(join(dir,f)) ]
onlyFiles.sort()

for game in onlyFiles:
	print("<item label=\"" + game + "\">")
	print("		<action name=\"Execute\">")
	print("			<execute>"+ dir + game +"</execute>")
	print("		</action>")
	print("</item>")


