#!/bin/bash
#TO DO: Convert to bash. Include cb-include.cfg!

if ! . cb-include.cfg 2> /dev/null; then
    echo '<openbox_pipe_menu>'
    echo '	<item label="Failed to locate cb-include.cfg in PATH">'
    echo '		<action name="Execute">'
    echo '			<execute>sakura</execute>'
    echo '		</action>'
    echo '	</item>'
    echo '</openbox_pipe_menu>'
    exit 1
fi

FILES=$HOME/.PlayOnLinux/shortcuts/*

menuStart

for f in $FILES
do
	GAME=$(echo "${f##*/}")
	menuItem "$GAME" "playonlinux --run \"$GAME\""
done

menuEnd